Add, substract, format, compareTo
rinukkusu/simple_moment pull request #16
Opened 2020-06-03 10:57 UTC by stevenosse

- Added more functionnalities 

> 
> - **format** uses the **intl** package to format a date using a given format
> -  **add** adds time to the current moment instance's date
> - **substract** substracts time to the current moment instance's date
> - **compareTo** compares the current moment instance's date to the given date

- Added some documentation to new an existing methods
- Wrote more tests

2020-06-03 11:09 UTC, rinukkusu requested changes
Thank you for your contribution, looks good overall, but I'd love to see tests for the parts where calculations happen, too!

2020-06-03 11:09 UTC, rinukkusu commented on lib/src/simple_moment_base.dart
> +      _date.month - months - quarters * monthPerQuarter,
Please add tests for adding and subtracting with months and days, too, since you're doing some calculations there. 😄

2020-06-03 11:09 UTC, rinukkusu commented on lib/src/simple_moment_base.dart
> +  int get quarter => (_date.month - 1) ~/ 3 + 1;
Please add a test for this getter as well.

2020-06-05 15:53 UTC, stevenosse commented
Thanks for reviewing. I've just added the test elements you've asked.

2020-06-06 07:52 UTC, rinukkusu approved these changes

2020-06-06 07:52 UTC, merged

2020-06-06 08:04 UTC, rinukkusu commented
`1.0.5` is out 😸